### ISSUE TITLE
1グリッドの長さが一般的な音楽制作ソフトと比べ4分の1となっている

### ISSUE THREAD

**Issue by jirno7pr** [setchi/NoteEditor#6]
NoteEditorの1グリッドの長さが、一般的な音楽制作ソフトと比べ4分の1となっています。

NoteEditorで数字から伸びる白線のグリッドを`メイングリッド`、
メイングリッドの間でLPBによって変わるグリッドを`サブグリッド`として説明します。

## 1. NoteEditorのグリッド単位
①メイングリッドは`4分音符`を表します。
②サブグリッドは`16分音符`（4 分音符 / LPB）を表します。

下画像のように、BPM120、4分音符、4回の波形を入力した場合、
**1つのメイングリッド間に1波形（＝4分音符1つ）が収まります。**
![noteeditor1](https://user-images.githubusercontent.com/42739586/62202451-4ab74f00-b3c4-11e9-90b2-a409696da5ac.png)

## 2. 一般的な音楽制作ソフトのグリッド単位
①メイングリッドは`全音符`を表します。
②サブグリッドは`4分音符`を表します。

[1. NoteEditorのグリッド単位]と同様に、BPM120、4分音符、4回の波形を入力した場合、
**１つのメイングリッド間に4波形（＝4分音符4つ→全音符）が収まります。**
![studiione](https://user-images.githubusercontent.com/42739586/62202493-599e0180-b3c4-11e9-8577-73665bec7c13.png)

## 結論
このように、一般的な音楽制作ソフトでは1つのメイングリッド＝全音符であるのに対し、
NoteEditorでは1つのメイングリッド＝4分音符のため、1グリッドの長さが4分の1となっています。

## お願い事項
本件仕様の場合、NoteEditorの1グリッドの長さを自分で改変して使用したいと考えております。
しかしソースコードを追ったのですが、変更箇所の見当を付けられていない状況です。
大まかで構いませんので、グリッドの長さの変更方法をご教示頂くことは出来ないでしょうか。

また、不具合の場合、修正して頂くことは出来ないでしょうか。

尚、NoteEditorのBPM設定で、BPMを実態の4分の1に設定すると、
[2. 一般的な音楽制作ソフトのグリッド単位]と同等の表示となります。
![noteeditor2](https://user-images.githubusercontent.com/42739586/62202510-5f93e280-b3c4-11e9-9829-18207cd3f2d1.png)

以上、よろしくお願いいたします。

**Comment by setchi** [comment]
@jirno7pr 
ご報告ありがとうございます。実装当時、音楽知識が乏しくこのような実装になっていました。
一般的な音楽ソフトと合わせた方がわかりやすいため、ご報告の通り修正させていただきました。

また、`GridLineRenderer` コンポーネント経由で各グリッドの色が変更できます。

<img width="599" alt="Screen Shot 2019-07-31 at 23 55 52" src="https://user-images.githubusercontent.com/8326814/62222713-c7f7b980-b3ee-11e9-93b9-a6fbde83fffe.png">

**Comment by jirno7pr** [comment]
@setchi 
早速のご対応ありがとうございました。
色の変更方法もご教示頂きありがとうございました。
クローズ致します。
