### ISSUE TITLE
offsetの単位を教えてほしいです

### ISSUE THREAD

**Issue by KentaKomai** [setchi/NoteEditor#7]
お世話になっております。NoteEditorを使って音ゲー制作に挑戦しているものです。
issueというよりは、質問になるんですが、エディタ上で設定できるoffsetの値の単位は何になりますでしょうか？

ミリ秒かと思い、それを譜面のtimingにあててみたのですが、意図したタイミングで反応せず
ご都合よろしいときにご教授いただけないでしょうか。

お願い致します。

**Comment by KentaKomai** [comment]
または `offset` を `timing` (秒)に加算するために必要な計算はどのように行えばよろしいでしょうか？

**Comment by setchi** [comment]
@KentaKomai 
offset の値は、当時の実装都合で NoteEditor で読み込んだ音源のサンプル周波数になっています。
https://docs.unity3d.com/jp/current/ScriptReference/AudioClip-frequency.html

例えば 44.1kHz なら 44100 で 1秒 となります。

**Comment by KentaKomai** [comment]
早いお返事ありがとうございます！！！！！
非常に助かりました！クローズとさせていただきます！！
